### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by cranes-bill**
I'm not sure about replacing the image will be done, so i'm attaching it here:
key

### CODE REVIEW

**Comment by nowrep** [comment]
I don't understand, what are you not sure of?
Why did you add key.png.md? Is there any reason for it?

**Comment by cranes-bill** [comment]
I just wanted to replace the image, but failed to understand how to do that (stupid me).
„key.png.md“ must not be there, but just new image.
Sorry and thank you!

**Comment by nowrep** [comment]
So you want me to fix it? Ok, I'll do it.

**Comment by cranes-bill** [comment]
Yes, many thanks!

**Pull request closed without merging**
