### PR TITLE
New Edge browser similar theme

### PR DESCRIPTION
**Pull request by cranes-bill**
capture du 2017-02-03 19-06-30

### CODE REVIEW

**Comment by nowrep** [comment]
Why is the tab title cropped at the screenshot?

Also, did you test it with HighDPI? `QT_SCALE_FACTOR=2 qupzilla`

**Comment by cranes-bill** [comment]
>Why is the tab title cropped at the screenshot?

Even i was not mentioned that.

>Also, did you test it with HighDPI? QT_SCALE_FACTOR=2 qupzilla

Unfortunately i don't have such a big screen right now, and i don't know what you have on mind here, so i'm closing this PR for now.

**Comment by nowrep** [comment]
> Unfortunately i don't have such a big screen right now, and i don't know what you have on mind here, so i'm closing this PR for now.

You don't have to close it. Just run `QT_SCALE_FACTOR=2 qupzilla` and check if everything looks fine (eg. everything should be scaled x 2, but also looks sharp and not pixelated).

**Comment by cranes-bill** [comment]
Hm, i don't know what causing this issue...

**Comment by cranes-bill** [comment]
@nowrep, please close that! I don't have time for it just right now. Also in general it was very stupid idea.

**Comment by cranes-bill** [comment]
#73

**Pull request closed without merging**
