### PR TITLE
Added Simple Session Manager plugin.

### PR DESCRIPTION
**Pull request by srazi**
- Needs pull request QupZilla/qupzilla#2280
- Closes QupZilla/qupzilla#759
- Closes QupZilla/qupzilla#1664
- Closes QupZilla/qupzilla#2243

### CODE REVIEW

**Comment by nowrep** [comment]
To be honest, I would like to see it as a core feature (or at least as plugin in main repo if you don't feel like rewriting it).

**Comment by nowrep** [comment]
Also, it looks like opening new session means just creating new windows (it doesn't close current session), am I right?

**Comment by srazi** [comment]
> Also, it looks like opening new session means just creating new windows (it doesn't close current session), am I right?

Yeah it open sessions in new windows without touching the current session.

**Comment by nowrep** [comment]
I would like to change it, because as it is now, as soon as it saves the session, it will merge the two sessions into one.
So ideally it should save the current session, close it and open the selected one.

**Comment by srazi** [comment]
> So ideally it should save the current session, close it and open the selected one.

This is more like switching session. How if add a new action like "open in current session"?
So "open" work as you said and "open in current session" work like what it do now.

**Comment by nowrep** [comment]
That sounds good, having both "open" and "switch" actions.

**Comment by srazi** [comment]
@nowrep How does `switch` action should work?
Saving current session to default session (session.dat) is not the correct solution as after loading the new session, `session.dat` will overwritten by `autosaver`. Maybe after saving to default session (session.dat) we should also run `backupSavedSessions()` ?

As another option we can do something like Qt Creator and save current session to the current active session. Also, we have to change the current QupZilla code in a way that  `autosaver` save the current active session. Of course, using this option session manager has to be a core feature.

**Comment by cranes-bill** [comment]
Hi @srazi, thank you that you were getting time for that! I would like to try it, but i'm  failing to compile it. The reason probably is old compiler version `gcc (GCC) 4.8.5 20150623` The error is following:

```
In file included from ssm_plugin.cpp:18:0:
ssm_plugin.h:42:59: erreur: could not convert ‘QString()’ from ‘QString’ to ‘QString&’
     void renameSession(QString &sessionFilePath = QString(), bool copy = false);
                                                           ^
ssm_plugin.cpp: In member function ‘void SSM_Plugin::backupSession()’:
ssm_plugin.cpp:150:50: erreur: no matching function for call to ‘SSM_Plugin::renameSession(QString, bool)’
     renameSession(action->data().toString(), true);
                                                  ^
ssm_plugin.cpp:150:50: note: candidate is:
ssm_plugin.cpp:106:6: note: void SSM_Plugin::renameSession(QString&, bool)
 void SSM_Plugin::renameSession(QString &sessionFilePath, bool copy)
      ^
ssm_plugin.cpp:106:6: note:   no known conversion for argument 1 from ‘QString’ to ‘QString&’
```

Can someone advise me how to workaround that error, please!

**Comment by srazi** [comment]
@cranes-bill Hi, indeed I am rewriting it as a core feature. About the issue you can remove `&` from `renameSession()` in both header and source file.

**Comment by cranes-bill** [comment]
@srazi Thank you very much! Yes, as core feature would be better.
Just to say, i also prefer restored session to be opened in current window instead of new one.

**Comment by nowrep** [comment]
> @nowrep How does switch action should work?

It should work like Qt Creator, as you described.

**Pull request closed without merging**
